= Управление индексами
:description: Управление индексами в OpenSearch
:source-language: http
:url-repo:

Вы можете индексировать данные с помощью OpenSearch REST API.
Для этого существуют два интерфейса: API индекса для добавления данных по одному элементу и API `_bulk` для пакетного добавления сразу нескольких элементов данных.

Если новые данные поступают постепенно (например, заказы клиентов в небольшой компании), вы можете использовать API индекса для добавления документов по отдельности по мере их поступления.
Если поток данных не такой частый (например, еженедельные обновления маркетингового сайта) целесообразнее генерировать файл и отправлять его в API `_bulk`.
При работе с большими объемами документов объединение запросов и использование API `_bulk` обеспечивает лучшую производительность.
Но если ваши документы очень большие, может потребоваться индексировать их по отдельности.

При индексации документов размер идентификатора (`_id`) документа не должен превышать 512 байт.

== Введение в индексацию

Чтобы данные стали доступны для поиска, их необходимо проиндексировать.
Индексация — это механизм, с помощью которого поисковые системы организуют данные для быстрого доступа к ним.
Результатом индексации является создание индекса.

В OpenSearch базовой единицей данных является JSON-документ.
Внутри индекса OpenSearch идентифицирует каждый документ с помощью уникального идентификатора.

Запрос к API индекса выглядит следующим образом:

[source]
----
PUT <index>/_doc/<id>
{ "A JSON": "document" }
----


Запрос к API `_bulk` отличается тем, что название индекса и идентификатор документа передаются не в URL-части, а в теле запроса в составе пакетных данных:

[source]
----
POST _bulk
{ "index": { "_index": "<index>", "_id": "<id>" } }
{ "A JSON": "document" }
----


Пакетные данные должны соответствовать определенному формату, где каждая строка, включая последнюю, должна заканчиваться символом новой строки (`\n`).
Например:

[source]
----
Действие и метаданные\n
Опциональный документ\n
Действие и метаданные\n
Опциональный документ\n
----


NOTE: Документ опционален, так как действие `delete` (удаление) не требует указания документа.
Все остальные действия (`index`, `create` и `update`) требуют передачи документа.
Если вы хотите, чтобы действие завершилось ошибкой, если документ уже существует, используйте действие `create` вместо `index`.

Чтобы выполнить пакетную индексацию данных с помощью команды curl, перейдите в папку с сохраненным файлом и выполните следующую команду:

[source,curl]
----
curl -H "Content-Type: application/x-ndjson" -POST https://localhost:9200/data/_bulk -u 'admin:admin' --insecure --data-binary "@data.json"
----

Если какое-либо действие в API `_bulk` завершается ошибкой, OpenSearch продолжит выполнение остальных действий.
Чтобы определить причину ошибки, проверьте массив `items` в ответе.
Порядок элементов в массиве `items` соответствуют порядку действий, указанных в запросе.

OpenSearch автоматически создает индекс, когда вы добавляете документ в несуществующий индекс.
OpenSearch также автоматически генерирует идентификатор, если он не указан в запросе.
В следующем примере автоматически создается индекс `movies`, индексируется документ, и ему присваивается уникальный идентификатор:

[source,http]
----
POST movies/_doc
{ "title": "Spirited Away" }
----

У автоматической генерации идентификатора есть очевидный недостаток: поскольку идентификатор не указан в запросе на индексацию, вам потребуется отдельно узнавать его, если позже вы захотите изменить документ.
Кроме того, если выполнить этот запрос 10 раз, OpenSearch проиндексирует документ как 10 отдельных документов с уникальными идентификаторами.
Чтобы указать 1 в качестве идентификатора, используйте следующий запрос (обратите внимание на использование PUT вместо POST):

[source,http]
----
PUT movies/_doc/1
{ "title": "Spirited Away" }
----

Поскольку идентификатор указан явно, то даже при 10-кратном выполнении этой команды будет проиндексирован только один документ, а значение поля `_version` будет увеличиваться до 10.

По умолчанию индексы создаются с одним первичным шардом и одной репликой.
Чтобы использовать другие настройки, создайте индекс перед добавлением документов:

[source,http]
----
PUT more-movies
{ "settings": { "number_of_shards": 6, "number_of_replicas": 2 } }
----


== Требования к названиям индексов в OpenSearch

Для названий индексов в OpenSearch действуют следующие требования:

* Все буквы должны быть в нижнем регистре.

* Названия индексов не могут начинаться с подчеркивания (`_`) или дефиса (`-`).

* В именах не допускаются пробелы, запятые и следующие специальные символы:
        `:`, `"`, `*`, `+`, `/`, `\`, `|`, `?`, `#`, `>` и `<`


== Чтение данных

После индексации документа вы можете получить его, отправив GET-запрос по тому же адресу, который использовали для индексации:

[source,http]
----
GET movies/_doc/1

{
  "_index" : "movies",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "_seq_no" : 0,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "title" : "Spirited Away"
  }
}
----

Запрашиваемый документ содержится в объекте `_source`.
Если документ не найден, параметр `found` будет иметь значение `false`, а объекта `_source` не будет в ответе.

Для получения нескольких документов одной командой используйте действие `_mget`.
Формат запроса аналогичен `_bulk`: необходимо указать название индекса и идентификаторы документов в теле запроса:

[source,http]
----
GET _mget
{
  "docs": [
    {
      "_index": "<index>",
      "_id": "<id>"
    },
    {
      "_index": "<index>",
      "_id": "<id>"
    }
  ]
}
----

Чтобы получить только определенные поля документа, используйте следующий синтаксис:

[source,HTTP]
----
GET _mget
{
  "docs": [
    {
      "_index": "<index>",
      "_id": "<id>",
      "_source": "field1"
    },
    {
      "_index": "<index>",
      "_id": "<id>",
      "_source": "field2"
    }
  ]
}
----

Чтобы проверить, что документ существует, используйте следующий синтаксис:

[source,HTTP]
----
HEAD movies/_doc/<doc-id>
----


Если документ существует, вы получите ответ `200 OK`.
В противном случае вы получите ошибку `404 - Not Found`.

== Изменение данных

Чтобы изменить существующие поля или добавить новые, отправьте POST-запрос к интерфейсу `_update` и в объекте `doc` укажите ваши изменения

[source,http]
----
POST movies/_update/1
{
  "doc": {
    "title": "Castle in the Sky",
    "genre": ["Animation", "Fantasy"]
  }
}
----

Обратите внимание на новые поля `title` и `genre` в ответе:

[source,http]
----
GET movies/_doc/1

{
  "_index" : "movies",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 2,
  "_seq_no" : 1,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "title" : "Castle in the Sky",
    "genre" : [
      "Animation",
      "Fantasy"
    ]
  }
}
----

Значение поля `_version` было увеличено на один.
Используйте это поле, чтобы понимать, сколько раз обновлялся документ.

POST-запросы используются для частичного изменения документа.
Чтобы заменить документ целиком, используйте PUT-запрос:

[source,http]
----
PUT movies/_doc/1
{
  "title": "Spirited Away"
}
----

Документ с идентификатором, равным 1, будет содержать только поле `title`, так как PUT-запрос полностью заменяет существующий документ новым.

Чтобы изменить документ в зависимости от того, существует он или нет, используйте объект `upsert`.
В примере ниже, если документ уже существует, значение поля `title` будет изменено на `Castle in the Sky`.
Если документ не существует, то будет проиндексирован документ из объекта `upsert`:

[source,http]
----
POST movies/_update/2
{
  "doc": {
    "title": "Castle in the Sky"
  },
  "upsert": {
    "title": "Only Yesterday",
    "genre": ["Animation", "Fantasy"],
    "date": 1993
  }
}
----

Пример ответа:

[source,json]
----
{
  "_index" : "movies",
  "_type" : "_doc",
  "_id" : "2",
  "_version" : 2,
  "result" : "updated",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 3,
  "_primary_term" : 1
}
----

Каждое действие по изменению документа имеет уникальную комбинацию значений `_seq_no` и `_primary_term`.

OpenSearch сначала записывает ваши изменения в основной шард, а затем отправляет эти изменения во все реплики.
Однако может возникнуть редкая проблема, если несколько пользователей вашего приложения, основанного на OpenSearch, одновременно обновляют документы в одном индексе.
В такой ситуации другой пользователь может получить и изменить документ из реплики до того, как эта реплика получит ваши изменения из основного шарда.
В результате ваше действие изменения применится к устаревшей версии документа.
В лучшем случае вы и другой пользователь внесете одинаковые изменения, и документ останется актуальным.
В худшем случае документ будет содержать устаревшую информацию.

Чтобы избежать этой ситуации, задайте значения `_seq_no` и `_primary_term` в заголовке запроса:

[source,http]
----
POST movies/_update/2?if_seq_no=3&if_primary_term=1
{
  "doc": {
    "title": "Castle in the Sky",
    "genre": ["Animation", "Fantasy"]
  }
}
----

Если документ изменяется после того, как мы его извлекли, значения `_seq_no` и `_primary_term` различаются, и действие изменения завершается ошибкой `409 — Conflict`.

При использовании API `_bulk` указывайте значения `_seq_no` и `_primary_term` в метаданных действия.


== Удаление данных

Чтобы удалить данные из индекса, используйте DELETE-запрос:

[source,http]
----
DELETE movies/_doc/1
----

Действие DELETE увеличивает значение поля `_version`.
Если вы снова добавите документ с тем же идентификатором, поле `_version` увеличится еще раз.
Так происходит потому, что OpenSearch удаляет `_source` документа, но сохраняет его метаданные.

== Дальнейшие шаги

* Плагин Index Management (IM) позволяет автоматизировать рутинные задачи управления индексами и снизить затраты на хранение.
Подробнее см. в разделе https://docs.opensearch.org/docs/latest/im-plugin/ism/index[Управление состоянием индексов].
* Инструкции по переиндексации данных см. в разделе https://docs.opensearch.org/docs/latest/im-plugin/reindex-data[Переиндексация данных].